version: '2'

services:
  db:
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: Bola1
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    image: "grupo02docker/inf323-utfsm-grupo02:latest"
    environment:
      DATABASE_URL: postgres://postgres_admin:Bola1@db/postgres_db
      REDIS_URL: redis://redis
      DJANGO_MANAGEPY_MIGRATE: "on"
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
